resources:
- ../base
nameSuffix: -prod
patches:
- path: overlay.yaml
  target:
    kind: Deployment
    labelSelector: app=metis
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: frank93011/metis
