apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: metis-container
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "200m"